#!/bin/sh /etc/rc.common
 
USE_PROCD=1
 
START=99
STOP=01
 
CONFIGURATION=smsgps

start_service() {
    # Reading config
    config_load "${CONFIGURATION}"
    local loglevel
 
    config_get loglevel log loglevel
 
    procd_open_instance
 
    # pass config to script on start
    procd_set_param command /bin/sh "/root/smsgps.sh" "$loglevel"
    procd_set_param file /etc/config/smsgps
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}